### ISSUE TITLE
Integration fails to start with HA 2023.2.1

### ISSUE THREAD

**Issue by p1ranha** [schlac/hacs-integration-discovergy#18] opened 2023-02-03 07:27 UTC
During startup following error occurs:

Logger: homeassistant.components.sensor
Source: custom_components/discovergy/sensor.py:256
Integration: Sensor (documentation, issues)
First occurred: 8:13:43 AM (1 occurrences)
Last logged: 8:13:43 AM

Error while setting up discovergy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/discovergy/sensor.py", line 228, in async_setup_entry
    DiscovergySensor(
  File "/config/custom_components/discovergy/sensor.py", line 256, in __init__
    self.precision = precision
AttributeError: can't set attribute 'precision'

HA:  2023.2.1
Integration version: 0.4.1

**Comment by p1ranha** [comment] 2023-02-03 08:00
Updating to latest beta, solves the problem though.

**Comment by schlac** [comment] 2023-02-03 08:11
Thanks for reporting, but this is a duplicate of #16 

With HA 2023.2 please use either `<= v0.3.0` or `>= v0.4.3`.

**Closed by schlac** 2023-02-03 08:11 UTC
